import { Plan } from '../types/plan.types';

export const AVAILABLE_PLANS: Plan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: 4999,
    monthlyPrice: 199,
    color: '#6b7280',
    icon: 'rocket-outline',
    description: 'Perfecto para comenzar tu negocio',
    maxUsers: 1,
    maxClients: 50,
    features: [
      'Hasta 50 clientes',
      'Agenda básica',
      'Notificaciones por email',
      'Soporte por email',
      '1 usuario',
      'Reportes básicos',
      'App móvil para clientes',
    ],
  },
  {
    id: 'professional',
    name: 'Professional',
    price: 9999,
    monthlyPrice: 399,
    color: '#3b82f6',
    icon: 'star',
    description: 'La mejor opción para negocios en crecimiento',
    recommended: true,
    maxUsers: 5,
    maxClients: 'unlimited',
    features: [
      'Clientes ilimitados',
      'Agenda avanzada',
      'Notificaciones SMS y email',
      'Soporte prioritario 24/7',
      'Hasta 5 usuarios',
      'Reportes y analytics',
      'Personalización de marca',
      'Integración con redes sociales',
      'Pagos online',
      'App móvil personalizada',
      'Recordatorios automáticos',
      'Sistema de fidelización',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 19999,
    monthlyPrice: 799,
    color: '#8b5cf6',
    icon: 'business',
    description: 'Solución completa para grandes empresas',
    maxUsers: 'unlimited' as any,
    maxClients: 'unlimited',
    features: [
      'Todo de Professional',
      'Usuarios ilimitados',
      'API personalizada',
      'Soporte dedicado',
      'Training personalizado',
      'Multi-sucursal',
      'Facturación automática',
      'Integración con CRM',
      'Backups dedicados',
      'SLA garantizado',
      'Personalización avanzada',
      'Consultoría de negocio',
    ],
  },
];

export const BUSINESS_TYPES = [
  { id: 'salon', name: 'Salón de Belleza', icon: 'cut-outline' },
  { id: 'barbershop', name: 'Barbería', icon: 'cut' },
  { id: 'spa', name: 'Spa', icon: 'flower-outline' },
  { id: 'clinic', name: 'Clínica', icon: 'medical-outline' },
  { id: 'gym', name: 'Gimnasio', icon: 'fitness-outline' },
  { id: 'restaurant', name: 'Restaurante', icon: 'restaurant-outline' },
  { id: 'hotel', name: 'Hotel', icon: 'bed-outline' },
  { id: 'other', name: 'Otro', icon: 'business-outline' },
];
